name 'chef_chocolatey'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures chef_chocolatey'
version '0.1.0'
chef_version '>= 15.0'
issues_url 'https://github.com/petesisk/chef_chocolatey/issues'
source_url 'https://github.com/petesisk/chef_chocolatey'

depends 'chocolatey'
depends 'ohai'
